[tool.poetry]
name = "bvr"
version = "0.1.0"
description = "Banch video recoder"
authors = ["Axis Pod <axispod@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
